### ISSUE TITLE
Exception in latest Brackets code

### ISSUE THREAD

**Issue by redmunds** [iwehrman/brackets-kill-ring#2]
I tried this out in the latest Brackets code, and I'm getting an exception because 'last_yank_end' is null:

I've never used kill ring before, so maybe I'm not using it correctly (C-k followed by M-y), but seems it should throw an exception.

---

Uncaught TypeError: Cannot read property 'line' of null extensions/dev/brackets-kill-ring-master/main.js:167
yank_pop extensions/dev/brackets-kill-ring-master/main.js:167
Command.execute command/CommandManager.js:89
execute command/CommandManager.js:237
executeCommand utils/ShellAPI.js:47

**Comment by iwehrman** [comment]
Thanks @redmunds!
